name: Générer des données
on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Tâches pour mettre à jour les données
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: J2mCoder
          svg_out_path: dist/github-contribution-grid-snake.svg

      #- uses: crazy-max/ghaction-github-pages@v4
      #with:
      #target_branch: output
      #build_dir: dist
      #env:
      #GITHUB_TOKEN: ${{ secrets.PRSONAL_GITHUB_TOKEN }}
